# Generated by Django 2.2.5 on 2020-02-18 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('ID', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('Name', models.CharField(max_length=50)),
                ('Department', models.CharField(choices=[('Cse', 'CSE'), ('Soft', 'SWE'), ('cis', 'CIS'), ('other', 'Other')], default='Cse', max_length=10)),
                ('Campus', models.CharField(choices=[('Main', 'MC'), ('Uttara', 'UC')], default='Main', max_length=10)),
                ('Semester', models.CharField(choices=[('first', '1st'), ('second', '2nd')], default='first', max_length=5)),
                ('Shift', models.CharField(choices=[('day', 'Day'), ('eve', 'Evening')], default='day', max_length=10)),
                ('Section', models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D'), ('e', 'E')], max_length=5)),
                ('TShirt', models.CharField(choices=[('mid', 'M'), ('large', 'L'), ('xlarge', 'XL'), ('xxlarge', 'XXL'), ('xxxlarge', 'XXXL')], default='mid', max_length=5)),
                ('Status', models.BooleanField(default=False)),
            ],
        ),
    ]
