# Generated by Django 2.2.5 on 2020-02-18 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Token',
            field=models.IntegerField(auto_created=True, default=1001),
        ),
        migrations.AlterField(
            model_name='student',
            name='Section',
            field=models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D'), ('e', 'E')], max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='Semester',
            field=models.CharField(choices=[('first', '1st'), ('second', '2nd')], default='first', max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='TShirt',
            field=models.CharField(choices=[('mid', 'M'), ('large', 'L'), ('xlarge', 'XL'), ('xxlarge', 'XXL'), ('xxxlarge', 'XXXL')], default='mid', max_length=10),
        ),
    ]
