# Generated by Django 2.2.5 on 2020-02-18 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0002_auto_20200218_1936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='Token',
        ),
    ]
