# Generated by Django 2.2.5 on 2020-02-19 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0003_remove_student_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contestant',
            fields=[
                ('Token', models.AutoField(auto_created=True, default=1001, primary_key=True, serialize=False, unique=True)),
                ('TShirt', models.CharField(choices=[('mid', 'M'), ('large', 'L'), ('xlarge', 'XL'), ('xxlarge', 'XXL'), ('xxxlarge', 'XXXL')], default='mid', max_length=10)),
                ('ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Registration.Student')),
            ],
        ),
    ]
