# Generated by Django 2.2.5 on 2020-02-19 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0004_contestant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestant',
            name='Token',
            field=models.AutoField(default=1001, primary_key=True, serialize=False, unique=True),
        ),
    ]
