# Generated by Django 2.2.5 on 2020-02-19 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0005_auto_20200219_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestant',
            name='Token',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, unique=True),
        ),
    ]
