# Generated by Django 2.2.5 on 2020-02-24 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0006_auto_20200219_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestant',
            name='TShirt',
            field=models.CharField(choices=[('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL')], default='mid', max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='Campus',
            field=models.CharField(choices=[('MC', 'MC'), ('UC', 'UC')], default='Main', max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='Department',
            field=models.CharField(choices=[('CSE', 'CSE'), ('SWE', 'SWE'), ('CIS', 'CIS'), ('Other', 'Other')], default='Cse', max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='Section',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='Semester',
            field=models.CharField(choices=[('1st', '1st'), ('2nd', '2nd')], default='first', max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='Shift',
            field=models.CharField(choices=[('Day', 'Day'), ('Evening', 'Evening')], default='day', max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='TShirt',
            field=models.CharField(choices=[('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL')], default='mid', max_length=10),
        ),
    ]
