# Generated by Django 3.0.3 on 2020-04-05 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0008_userprofileinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfileInfo',
        ),
    ]
