# Generated by Django 3.0.3 on 2020-04-17 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0010_auto_20200413_1945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='TShirt',
        ),
        migrations.AlterField(
            model_name='contestant',
            name='TShirt',
            field=models.CharField(choices=[('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL')], default='M', max_length=10),
        ),
        migrations.AlterField(
            model_name='contestant',
            name='Token',
            field=models.AutoField(auto_created=True, default=1001, primary_key=True, serialize=False, unique=True),
        ),
    ]
